# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Maven Central

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy_util:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.MAVEN_SIGNING_KEY }}
        passphrase: ${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        server-id: maven-central-release
        server-username: MVN_CENTRAL_USERNAME
        server-password: MVN_CENTRAL_PASSWORD

    - name: Publish to Maven Central
      run: |
        mvn --file pom.xml -P release -Dgpg.keyname=${{ secrets.GPG_KEY_NAME }} -Dgpg.passphrase=${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }} \
          -Drevision=${{ steps.calculate-version.outputs.version-string }} -Dgpg.skip=false deploy
      env:
        MVN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MVN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
